package com.guo.springboot.domain;

import java.util.Date;

public class Profile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.id
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.username
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.password
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.mobile
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.address
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.update_by
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    private Integer updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.created_by
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.update_time
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.created_time
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.id
     *
     * @return the value of profile.id
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.id
     *
     * @param id the value for profile.id
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.username
     *
     * @return the value of profile.username
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.username
     *
     * @param username the value for profile.username
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.password
     *
     * @return the value of profile.password
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.password
     *
     * @param password the value for profile.password
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.mobile
     *
     * @return the value of profile.mobile
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.mobile
     *
     * @param mobile the value for profile.mobile
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.address
     *
     * @return the value of profile.address
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.address
     *
     * @param address the value for profile.address
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.update_by
     *
     * @return the value of profile.update_by
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.update_by
     *
     * @param updateBy the value for profile.update_by
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.created_by
     *
     * @return the value of profile.created_by
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.created_by
     *
     * @param createdBy the value for profile.created_by
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.update_time
     *
     * @return the value of profile.update_time
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.update_time
     *
     * @param updateTime the value for profile.update_time
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.created_time
     *
     * @return the value of profile.created_time
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.created_time
     *
     * @param createdTime the value for profile.created_time
     *
     * @mbggenerated Fri Apr 13 10:37:23 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}