package com.guo.springboot.domain;

public class TimeTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_task.id
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_task.order_no
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    private Long orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_task.slot_index
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    private Integer slotIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_task.id
     *
     * @return the value of time_task.id
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_task.id
     *
     * @param id the value for time_task.id
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_task.order_no
     *
     * @return the value of time_task.order_no
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_task.order_no
     *
     * @param orderNo the value for time_task.order_no
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_task.slot_index
     *
     * @return the value of time_task.slot_index
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    public Integer getSlotIndex() {
        return slotIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_task.slot_index
     *
     * @param slotIndex the value for time_task.slot_index
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    public void setSlotIndex(Integer slotIndex) {
        this.slotIndex = slotIndex;
    }
}