package com.guo.springboot.dao;

import com.guo.springboot.domain.TimeTask;
import com.guo.springboot.domain.TimeTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimeTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    int countByExample(TimeTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    int deleteByExample(TimeTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    int insert(TimeTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    int insertSelective(TimeTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    List<TimeTask> selectByExample(TimeTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    TimeTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") TimeTask record, @Param("example") TimeTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    int updateByExample(@Param("record") TimeTask record, @Param("example") TimeTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    int updateByPrimaryKeySelective(TimeTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_task
     *
     * @mbggenerated Sun Aug 05 14:35:51 CST 2018
     */
    int updateByPrimaryKey(TimeTask record);
}